- name: Provision a set of EC2 instances with tag_Name {{ ec2_scope }}
  ec2:
     key_name: "{{ ec2_key_name }}"
     state: present
     region: "{{ ec2_region }}"
     instance_type: "{{ ec2_size }}"
     image: "{{ ec2_ami }}"
     group: "{{ ec2_sg }}"
     vpc_subnet_id: "{{ vpc_subnet_id }}"
     assign_public_ip: "{{ ec2_assign_public_ip }}"
     wait: "{{ ec2_wait }}"
     count: "{{ ec2_count }}"
     instance_tags: "{{ ec2_instance_tags }}"
  register: ec2
