---
# tasks file for ec2
- name: 'Include AWS EC2 security group tasks'
  include_tasks: ec2_sgcreate.yml
- name: 'Including AWS EC2 instance create tasks'
  include_tasks: ec2_instcreate.yml
- name: 'Adding EC2 hosts to the in memory inventory'
  include_tasks: ec2_add_hosts.yml
